### ISSUE TITLE
Lacking in font department

### ISSUE THREAD

**Issue by shehi** [mislam/dotfiles#5]
This package heavily lacks in font department: using the font provided has special character related issues. Packages like Symfony CLI have strong table-like, colored output capabilities. With the font included, tables have no boundaries etc. The new glyphs introduced in this special font need to be placed in special address ranges, and not overwrite an address which is already occupied by a UTF-8 charset character. @mislam , please fix the font issue, otherwise this package becomes useless for devs who utilize terminal a lot.

**Comment by shehi** [comment]
Example characters are: ─ ┴ ┘┤etc
The font provided in this package lacks these glyphs.

**Comment by shehi** [comment]
Update: I compared FiraCode-Regular to Ubuntu-Mono:

![image](https://cloud.githubusercontent.com/assets/653569/17144192/9f96adaa-535e-11e6-949d-a1232d2247b4.png)

Apparently, Fira-Code has the glyphs, but for some weird reason, they are not being printed. Look at these two examples:

![image](https://cloud.githubusercontent.com/assets/653569/17144239/be535fb8-535e-11e6-9a60-577e14738df3.png)

versus

![image](https://cloud.githubusercontent.com/assets/653569/17144249/c812ee56-535e-11e6-8990-a4381417e73c.png)

These issues need fixing.

**Comment by mislam** [comment]
If you are facing font related issue, please feel free to forward them to FiraCode repo:
https://github.com/tonsky/FiraCode/. Closing it.
